/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/renault_master_collider.glb --types -o Renault_master_collider.tsx 
*/

import React, { JSX, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'

export function RenaultMasterCollider(props: JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/renault_master_collider.glb')
  const colliderScene = useMemo(() => scene.clone(true), [scene])

  return (
    <group {...props} dispose={null}>
      <primitive object={colliderScene} />
    </group>
  )
}

useGLTF.preload('/renault_master_collider.glb')
