/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\Andreotti\Desktop\mmmv-van\van-pixels-project\public\renault_master_panel_van.glb --types 
Author: Nieve5677 (https://sketchfab.com/iori308408)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/renault-master-panel-van-b2148d8984144f1a8879ca4352bfccc9
Title: Renault Master Panel Van
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_40: THREE.Mesh
    Object_41: THREE.Mesh
    Object_42: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_47: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_52: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_56: THREE.Mesh
    Object_57: THREE.Mesh
    Object_58: THREE.Mesh
    Object_59: THREE.Mesh
    Object_60: THREE.Mesh
    Object_61: THREE.Mesh
    Object_62: THREE.Mesh
    Object_63: THREE.Mesh
    Object_64: THREE.Mesh
    Object_65: THREE.Mesh
    Object_66: THREE.Mesh
    Object_67: THREE.Mesh
    Object_68: THREE.Mesh
    Object_69: THREE.Mesh
    Object_70: THREE.Mesh
    Object_71: THREE.Mesh
    Object_72: THREE.Mesh
    Object_73: THREE.Mesh
    Object_74: THREE.Mesh
    Object_75: THREE.Mesh
    Object_76: THREE.Mesh
    Object_77: THREE.Mesh
    Object_78: THREE.Mesh
    Object_79: THREE.Mesh
  }
  materials: {
    mirror: THREE.MeshStandardMaterial
    orangeglass: THREE.MeshStandardMaterial
    redglass: THREE.MeshStandardMaterial
    LicPlate_black: THREE.MeshStandardMaterial
    LicPlate_blue: THREE.MeshStandardMaterial
    LicPlate_white: THREE.MeshStandardMaterial
    LicPlate_yellow: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    brakedisk: THREE.MeshStandardMaterial
    carpaint: THREE.MeshStandardMaterial
    chrome: THREE.MeshStandardMaterial
    clearglass: THREE.MeshStandardMaterial
    interior: THREE.MeshStandardMaterial
    mattemetal: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    tire: THREE.MeshStandardMaterial
    windowglass: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/renault_master_panel_van.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.mirror} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.orangeglass} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.redglass} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.LicPlate_black} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.LicPlate_blue} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.LicPlate_white} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.LicPlate_yellow} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.brakedisk} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.carpaint} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.carpaint} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.carpaint} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.carpaint} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.carpaint} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.clearglass} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.clearglass} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.clearglass} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.clearglass} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.interior} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.interior} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.mattemetal} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.orangeglass} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.redglass} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.redglass} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.redglass} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.windowglass} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.windowglass} />
      </group>
    </group>
  )
}

useGLTF.preload('/renault_master_panel_van.glb')
