/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/renault_master_collider.glb --types -o Renault_master_collider.tsx 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_30: THREE.Mesh
  }
  materials: {
    ['carpaint.002']: THREE.MeshStandardMaterial
  }
}

export function RenaultMasterCollider(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/renault_master_collider.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_30.geometry} material={materials['carpaint.002']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/renault_master_collider.glb')
